### ISSUE TITLE
Drop ``import React``

### ISSUE THREAD

**Issue by bigfatbird** [webbushka/atom-react-snippets#60]
React 17 does not rely on 
``
import React from 'react';
``
anymore.

**Comment by webbushka** [comment]
I hesitate to remove it, since everyone that uses this may not have migrated to React 17 yet (and it doesn't hurt anything to leave it in). A couple of options that I can think of in the meantime:

1. add another snippet that doesn't add that line
2. update the current snippets with the import section highlighted when tabbing through cursor points.

Let me know your thoughts on it...

**Comment by bigfatbird** [comment]
I added a custom snippet to my installation after solving #61. I just started react and have to learn a lot, though. 

If I continue using your plugin and need more I'll might work as a contributor/maintainer.
